### ISSUE TITLE
Server 2.9.4 + 2.9.5 with PCIE Coral dual edge TPU - Object Detection (Coral) 2.4.0 only utilising one TPU

### ISSUE THREAD

**Issue by cralwalker** [codeproject/CodeProject.AI-ObjectDetectionCoral#11]
**Area of Concern**
- [X] Server 2.9.4 + 2.9.5
- [X] Behaviour of one or more Modules: Object Detection (Coral) 2.4.0

**Describe the bug**
Only one of the dual TPUs are utilised after upgrading from server 2.6.5. 
TPU (TF-Lite) / CPU (TF-Lite)

**Expected behavior**
I expected both TPUs to be utilised as they were in server 2.6.5
Multi-TPU (TF-Lite)

**Your System:**
 - CodeProject.AI Server version: 2.9.4 + 2.9.5
 - OS: Windows 11 23H2
 - System RAM 16 GiB
 - GPU Intel(R) UHD Graphics 630
 - GPU RAM 1,024 MiB

**Additional context**
First pass I installed over server 2.6.5
Second pass I uninstalled server 2.9.4 and reinstalled server 2.9.4
Third pass I uninstalled server 2.9.4, deleted folder C:\Program Files\CodeProject and installed server 2.9.4
Fourth pass I uninstalled server 2.9.4, deleted folder C:\Program Files\CodeProject, reninstalled 'edgetpu_runtime_20221024' and installed server 2.9.4

The problem remain.

**Comment by jjones-sf** [comment]
Experiencing same issue.  Repeatedly seeing this:
objectdetection_coral_adapter.py: WARNING:root:No multi-TPU interpreters: Falling back to single-TPU/CPU detection

was working fine before i upgraded to CPAI 2.8.0 and Coral OD 2.4.0

**Comment by cralwalker** [comment]
Today, Multi-TPU (TF-Lite) is used. I have not made any modifications to my setup, it must be magic.

Thank you magic (thumb up)

**Comment by cralwalker** [comment]
@jjones-sf I hope it is resolved you as well.

**Comment by jjones-sf** [comment]
> @jjones-sf I hope it is resolved for you as well.
> 
> edit: construct a complete sentence..

I updated to 2.9.5 with coral 2.4.0 and still having issues unfortunately
